package model;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Szoftver projekt laboratórium: Sivatagi vízhálózat
//  @ File Name : Model.CountableObserved.java
//  @ Date : 2023. 03. 28.
//  @ Author : aD4B team
//
//


/**
 * Interfész, azok az osztályok, amik megvalósítják megfigyelhetőek egy Model.Observer által.
 */
public interface CountableObserved {

    /**
     * Felveszi a megfigyelői közé a paraméterként átvett Observert.
     *
     * @param obs regisztrálni kívánt obszerver
     */
    void registerObserver(Observer obs);

    /**
     * Törli az őt megfigyelő Observereket
     */
    void unregisterObservers();

    /**
     * Értesíti az őt megfigyelő Observereket
     */
    void notifyObservers(int water);
}
