//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Szoftver projekt laboratórium: Sivatagi vízhálózat
//  @ File Name : Model.Observer.java
//  @ Date : 2023. 03. 28.
//  @ Author : aD4B team
//
//

package model;


import org.apache.logging.log4j.Logger;
import proto.LogHelper;

public abstract class Observer {
	private static final Logger LOGGER = LogHelper.getLogger();
	/**
	 * Frissíti az Observert.
	 */
	public abstract void update(int water);
	
}
