package model;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Szoftver projekt laboratórium: Sivatagi vízhálózat
//  @ File Name : Model.Steppable.java
//  @ Date : 2023. 03. 28.
//  @ Author : aD4B team
//
//



/**
 * Interfész a pályán lévő elemek körönkénti léptetéséhez.
 */
public interface Steppable {
	/**
	 *  Lépteti a léptethető elemet.
	 */
	void step() ;
}
