package model.characters;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Szoftver projekt laboratórium: Sivatagi vízhálózat
//  @ File Name : Model.Saboteur.java
//  @ Date : 2023. 03. 28.
//  @ Author : aD4B team
//
//


import model.fields.Field;
import org.apache.logging.log4j.Logger;
import proto.LogHelper;

import java.util.ArrayList;

/**
 * Szabotőr játékost reprezentáló osztály. Képes a csövek kilyukasztására, pumpák átállítására.
 */
public class Saboteur extends Character {
    private static final Logger LOGGER = LogHelper.getLogger();

    public Saboteur(Field actField) {
        super(actField);
        LOGGER.info("SIKERES - saboteur sikeresen létrejött");
    }


    @Override
    public String toString() {
        return  "ID: \""+super.toString()+ "\" Pozíció: \""+(actField==null? "Null":actField.toString())+"\" GlueTimer: \""+glueTimer+"\"";
    }

    /**
     * Csúszóssá teszi a csövet, amelyiken a játékos áll.
     * Így aki rálép, véletlenszerűen a cső valamelyik végéhez kapcsolódó elemre kerül. Sikeres művelet esetén true a visszatérési értéke.
     * @return true, ha sikerült csúszóssá tenni a csövet
     */
    public boolean slipPipe(){
        if(actionPerformed){
            System.out.println("Már végrehajtott egy akciót ebben a körben!");
            LOGGER.debug("Nem hajthat végre akciót, (actionPerformed=true)");
            return false;
        }
        if(actField.makeSlippery()){
            LOGGER.info("SIKERES - saboteur sikeresen csúszóssá tette a csövet amin áll");
            LOGGER.debug("Pipe.isSlippery = true");
            actionPerformed=true;
            return true;
        } else{
            LOGGER.info("SIKERTELEN - saboteur nem tudta csúszóssá tenni a csövet amin áll");
            return false;
        }
}

    /**
     * Visszaadja a karakter által használható műveletetek
     */
    @Override
    public ArrayList<String> getCommands(){
        //a parancsok megadása string tömbben
        ArrayList<String> cmds = new ArrayList<>(super.getCommands());
        cmds.add("slippery");
        return cmds;
    }

}